name: Save OPI NET Prices Monthly

on:
  schedule:
    - cron: '10 0 2 * *'
    - cron: '10 0 3 * *'
    - cron: '10 0 4 * *'

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run price crawler
        run: python opinet_save.py

      - name: Commit and push JSON file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add *.json
          git commit -m "Save OPI NET prices for $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push
